"""empty message

Revision ID: 1a23fc06a80a
Revises: 
Create Date: 2023-10-24 16:02:06.109628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a23fc06a80a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('peso', sa.Float(), nullable=True),
    sa.Column('altura', sa.Float(), nullable=True),
    sa.Column('distancia_teste', sa.Float(), nullable=True),
    sa.Column('tempo_teste', sa.Float(), nullable=True),
    sa.Column('ja_corre', sa.Boolean(), nullable=True),
    sa.Column('km_corridos', sa.Float(), nullable=True),
    sa.Column('disponibilidade_treino', sa.String(length=255), nullable=True),
    sa.Column('data_nascimento', sa.Date(), nullable=True),
    sa.Column('objetivo_tempo', sa.Float(), nullable=True),
    sa.Column('objetivo_distancia', sa.Float(), nullable=True),
    sa.Column('data_objetivo_final', sa.Date(), nullable=True),
    sa.Column('classificacao', sa.String(length=255), nullable=True),
    sa.Column('volume_semanal_final', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
