"""empty message

Revision ID: c5db8dcb8a9c
Revises: 
Create Date: 2023-11-06 17:28:58.183284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5db8dcb8a9c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('telefone', sa.String(length=255), nullable=True),
    sa.Column('site', sa.String(length=255), nullable=True),
    sa.Column('estado', sa.String(length=255), nullable=True),
    sa.Column('cidade', sa.String(length=255), nullable=True),
    sa.Column('numero_de_atletas', sa.Integer(), nullable=True),
    sa.Column('data_cadastro', sa.Date(), nullable=True),
    sa.Column('senha', sa.String(length=255), nullable=True),
    sa.Column('token_de_resetar_senha', sa.String(length=255), nullable=True),
    sa.Column('data_de_expiracao_do_token_de_resetar_senha', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('telefone')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('peso', sa.Float(), nullable=True),
    sa.Column('altura', sa.Float(), nullable=True),
    sa.Column('distancia_teste', sa.Float(), nullable=True),
    sa.Column('tempo_teste', sa.Float(), nullable=True),
    sa.Column('ja_corre', sa.Boolean(), nullable=True),
    sa.Column('km_corridos', sa.Float(), nullable=True),
    sa.Column('disponibilidade_treino', sa.String(length=255), nullable=True),
    sa.Column('data_nascimento', sa.Date(), nullable=True),
    sa.Column('objetivo_tempo', sa.Float(), nullable=True),
    sa.Column('objetivo_distancia', sa.Float(), nullable=True),
    sa.Column('data_objetivo_final', sa.Date(), nullable=True),
    sa.Column('classificacao', sa.String(length=255), nullable=True),
    sa.Column('volume_semanal_final', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('treinador',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=True),
    sa.Column('sobrenome', sa.String(length=255), nullable=True),
    sa.Column('telefone', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('data_cadastro', sa.Date(), nullable=True),
    sa.Column('registro_profissional', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=255), nullable=True),
    sa.Column('senha', sa.String(length=255), nullable=True),
    sa.Column('assessoria_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['assessoria_id'], ['assessoria.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('telefone')
    )
    op.create_table('atleta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=True),
    sa.Column('sobrenome', sa.String(length=255), nullable=True),
    sa.Column('telefone', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('data_cadastro', sa.Date(), nullable=True),
    sa.Column('data_nascimento', sa.Date(), nullable=True),
    sa.Column('data_objetivo_final', sa.Date(), nullable=True),
    sa.Column('objetivo_distancia', sa.Float(), nullable=True),
    sa.Column('velocidade_objetivo', sa.Float(), nullable=True),
    sa.Column('dias_de_treino', sa.String(length=255), nullable=True),
    sa.Column('disponibilidade_diaria', sa.String(length=255), nullable=True),
    sa.Column('volume_semanal_atual', sa.Float(), nullable=True),
    sa.Column('volume_semanal_final', sa.Float(), nullable=True),
    sa.Column('assessoria_id', sa.Integer(), nullable=False),
    sa.Column('treinador_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['assessoria_id'], ['assessoria.id'], ),
    sa.ForeignKeyConstraint(['treinador_id'], ['treinador.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('telefone')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('atleta')
    op.drop_table('treinador')
    op.drop_table('user')
    op.drop_table('assessoria')
    # ### end Alembic commands ###
